"""add_external_id

Revision ID: 45105ab24e1b
Revises: 3737644ac31c
Create Date: 2026-06-27 07:31:02.725381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45105ab24e1b'
down_revision: Union[str, Sequence[str], None] = '3737644ac31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_external_id'), 'payments', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_external_id'), table_name='payments')
    op.drop_column('payments', 'external_id')
    # ### end Alembic commands ###
