"""add processed_payments table

Revision ID: dee77747f6d6
Revises: dc70d91c4456
Create Date: 2026-06-26 15:05:58.087536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee77747f6d6'
down_revision: Union[str, Sequence[str], None] = 'dc70d91c4456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_payments',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_payments'))
    )
    op.create_index(op.f('ix_processed_payments_payment_id'), 'processed_payments', ['payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_payments_payment_id'), table_name='processed_payments')
    op.drop_table('processed_payments')
    # ### end Alembic commands ###
